# Generated by Django 4.2.15 on 2024-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitynews',
            name='content_summary',
            field=models.TextField(default=12333),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitynews',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
